0414_practice/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eithers/', include('eithers.urls')),
]

0414_practice/eithers/urls.py
from django.urls import path
from . import views


app_name = 'eithers'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('random/', views.random, name='random'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:question_pk>/comments/', views.comment_create, name='comment_create'),
]

0414_practice/eithers/models.py
from random import choices
from django.db import models

class Question(models.Model):
    title = models.CharField(max_length=50)
    issue_a = models.CharField(max_length=20)
    issue_b = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    que = models.ForeignKey(Question, on_delete=models.CASCADE)
    content =  models.CharField(max_length=200)
    pick = models.CharField(max_length=20)

    def __str__(self):
        return self.content

0414_practice/eithers/forms.py
from tkinter import Widget
from django import forms
from .models import Question, Comment

class QuestionForm(forms.ModelForm):

    title = forms.CharField(
        max_length=50,
        label = "Title",
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control'
            }
        )
    )

    issue_a = forms.CharField(
        max_length=20,
        label = "Issue a",
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control'
            }
        )
    )


    issue_b = forms.CharField(
        max_length=20,
        label = "Issue b",
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control'
            }
        )
    )


    class Meta:
        model = Question
        fields = '__all__'



class CommentForm(forms.ModelForm):

    pick_A = "Blue"
    pick_B = "Red"
    pick_choice = [
        (pick_A, 'Blue'),
        (pick_B, 'Red'),
    ]

    pick = forms.ChoiceField(
        label = "pick",
        choices = pick_choice,
        widget=forms.Select(
            attrs={
                'class' : 'form-select'
            }
        )
    )

    content = forms.CharField(
        max_length=100,
        label = "content",
        widget=forms.TextInput(
            attrs = {
                'class' : 'form-control'
            }
        )
    )

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('que',)

0414_practice/eithers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from eithers.forms import QuestionForm, CommentForm
from .models import Question, Comment
from random import *

# 메인화면
def index(request):
    questions = Question.objects.order_by('-pk')
    context = {
        'questions': questions,
    }
    return render(request, 'eithers/index.html', context)

# 랜덤 페이지 번호 생성
def random(request):
    q_num = Question.objects.count()
    num = randint(1, q_num)

    return redirect('eithers:detail', num)


# 글작성
def create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():  # 유효성 검사
            question = form.save()
            return redirect('eithers:index')
    else:
        form = QuestionForm()
    context = {
        'form': form,
    }
    return render(request, 'eithers/create.html', context)


@require_safe
def detail(request, pk):
    
    question = get_object_or_404(Question, pk=pk)
    comment_form = CommentForm()
    comments = question.comment_set.all()
    if comments.count() != 0:
        Red = round((comments.filter(pick = 'Red').count())/comments.count() * 100, 2)
        Blue = round((comments.filter(pick = 'Blue').count())/comments.count() * 100, 2)

    else:
        Red = 0
        Blue = 0

    context = {
        'question': question,
        'comment_form' : comment_form,
        'comments' : comments,
        'Red' : Red,
        'Blue' : Blue,
    }

    return render(request, 'eithers/detail.html', context)

@require_POST
def comment_create(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.que = question
        comment.save()
    return redirect('eithers:detail', question.pk)

    
    

0414_practice/eithers/templates/eithers/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <button type="button" class="btn btn-outline-primary card-link me-2" onclick="location.href='{% url 'eithers:index' %}'">Back</button>
  <hr>
  <form action="{% url 'eithers:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content %}

0414_practice/eithers/templates/eithers/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Detail</h1>
  <button type="button" class="btn btn-outline-danger card-link me-2" onclick="location.href='{% url 'eithers:random' %}'">Random Question</button>
  <button type="button" class="btn btn-outline-primary card-link me-2" onclick="location.href='{% url 'eithers:index' %}'">Back</button>
  <hr>
  
  <h1 class="text-center">{{ question.title }}</h1>
  <br>
  <div class="d-flex justify-content-between">
    <h2 class="text-primary">{{ question.issue_a }}</h2>
    <h2 class="text-danger">{{ question.issue_b }}</h2>
  </div>
  <hr>
  {% if comments.count != 0 %}
    <div class="progress" style="height: 50px;">
      <div class="progress-bar progress-bar-striped fs-4" role="progressbar"  style="width: {{ Blue }}%" aria-valuemin="0" aria-valuemax="100" f> {{ Blue }} </div>
      <div class="progress-bar progress-bar-striped bg-danger fs-4" role="progressbar" style="width: {{ Red }}%"  aria-valuemin="0" aria-valuemax="100">{{ Red }} </div>
    </div>
    <hr>
  {% endif %}

  
  <h3>댓글 작성</h3>
    <form action="{% url 'eithers:comment_create' question.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <br>
      <button type="submit" class="btn btn-warning">작성</button>
    </form>

  <hr>


  <h3>댓글 목록</h3>
    {% for comment in comments %}
    {% if  comment.pick == 'Blue'%}
      <div class="p-3 mb-2 bg-primary bg-opacity-50">
        <div style = "color:blue;">{{ comment.content }}</div>
        </div>
    {% else %}
    <div class="p-3 mb-2 bg-danger bg-opacity-50">
      <div class="text-danger">{{ comment.content }}</div>
      </div>
    {% endif %}
      
      <hr>
    {% endfor %}
  
{% endblock content %}

0414_practice/eithers/templates/eithers/index.html
{% extends 'base.html' %}

{% block content %}

  <h1>Either Game</h1>
  <button type="button" class="btn btn-primary card-link me-2" onclick="location.href='{% url 'eithers:create' %}'">New Question</button>
  <button type="button" class="btn btn-danger card-link me-2" onclick="location.href='{% url 'eithers:random' %}'">Random Question</button>
 
  <hr>

  <ul class="list-group" style="width: 300px;">
    {% for question in questions%}
    <li class="list-group-item ">
    <h4>{{ question.title }}</h4>
    <button type="button" class="btn btn-warning card-link me-2" onclick="location.href='{% url 'eithers:detail' question.pk %}'">play</button>
  </li>
    {% endfor %}
  <ul>
{% endblock content %}

0414_practice/templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  {% bootstrap_javascript %}
</body>
</html>